---

- name: update apt package cache
  apt: update_cache=yes cache_valid_time=36000 

- name: add PPA for redis
  apt_repository: repo='ppa:chris-lea/redis-server'

- name: install common packages debian/ubuntu
  become: true
  become_user: root
  apt: pkg={{ item }} state=latest
  with_items:
    - build-essential
    - python-setuptools
    - python-dev
    - python3.4-dev
    - libxslt1-dev
    - libxml2-dev
    - libz-dev
    - libffi-dev
    - libssl-dev
    - libjpeg-dev
    - redis-server
    - python-psycopg2
    - python-pip
    - memcached
    - python-pycurl

- name: install pillow
  pip: name=pillow version=3.3.1

- include: supervisor.yml
- include: nginx.yml
  nginx_sites: none         
- include: postgreSQL.yml
- include: sentry.yml
